# Run `npm upgrade` and then `npm run fix` every week.
# If changes were made and the tests pass, commit the changes back.
name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: "* 2 * * SUN"
jobs:
  upgrade:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: install
        run: bun install
      - name: update
        run: bun update
      - name: fix
        run: bun run fix
      - name: test
        run: bun run test
      - name: git config
        env:
          BOT_USER_NAME: ${{ vars.BOT_USER_NAME }}
          BOT_USER_ID: ${{ vars.BOT_USER_ID }}
          BOT_PUBLIC_KEY: ${{ vars.BOT_PUBLIC_KEY }}
          BOT_PRIVATE_KEY: ${{ secrets.BOT_PRIVATE_KEY }}
        run: |
          mkdir ~/.ssh
          install -m 600 <(echo "$BOT_PUBLIC_KEY") ~/.ssh/git.pub
          install -m 600 <(echo "$BOT_PRIVATE_KEY") ~/.ssh/git
          eval `ssh-agent -s`
          ssh-add ~/.ssh/git
          git config user.name "${BOT_USER_NAME}"
          git config user.email "${BOT_USER_ID}+${BOT_USER_NAME}@users.noreply.github.com"
          git config --global gpg.format ssh
          git config --global user.signingkey ~/.ssh/git.pub
          git config --global commit.gpgsign true
      - name: git commit
        run: |
          git commit -am "chore: Update" && git push || echo "Nothing to commit"
